# Generated by Django 5.2.8 on 2025-11-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('solution1', models.CharField(max_length=50)),
                ('solution2', models.CharField(max_length=50)),
                ('solution3', models.CharField(max_length=50)),
                ('solution4', models.CharField(max_length=50)),
            ],
        ),
    ]
